/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import VectorImage from 'src/assets/images/RatingStar_Vector.png';
import { styled } from '@mui/material/styles';

 
const StarOutlined = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: `17px`,  
  height: `16px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Vector = styled("img")({  
  height: `16px`,  
  width: `17px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
 
function RatingStar(props) {
  return (
    <StarOutlined className={props.className} >
      <Vector  src={VectorImage} alt={"Vector"}/>
    </StarOutlined>
  );
}

export default RatingStar;
