/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import UnionImage from './assets/images/Union_7.png';
import PimcoFundsLogoBlackAImage from './assets/images/pimco_funds_logo_black_and_white_1_3.png';
import Image7Image from './assets/images/image_7_3.png';
import Image8Image from './assets/images/image_8_3.png';
import Image9Image from './assets/images/image_9_3.png';
import Image10Image from './assets/images/image_10_3.png';
import Image14Image from './assets/images/image_14_3.png';
import Image12Image from './assets/images/image_12_3.png';
import Image6Image from './assets/images/image_6_3.png';
import Image13Image from './assets/images/image_13_3.png';
import Union1Image from './assets/images/Union_6.png';
import { styled } from '@mui/material/styles';
import HeroImage from './assets/images/Hero_3.png';
import TopNav from './TopNav';
import NumberCallout from './NumberCallout';
import Buttons from './Buttons';
import FccButtons from './FccButtons';
import Footer from './Footer';
import useQ001Home from './useQ001Home';
 
const Q001Home1 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: `1441px`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
}));
  
const TopNav1 = styled(TopNav)(({ theme }) =>({  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
  
const Hero = styled("div")({  
  backgroundImage: `url(${HeroImage})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `64px 273px 64px 132px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `740px`,  
  margin: `0px`,  
});
  
const FitchCreditCertifica = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `500`,  
  fontSize: `56px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `64px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
  
const Q78OfCertifiedProfes = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(168, 168, 168, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Text`,  
  fontWeight: `500`,  
  fontSize: `18px`,  
  letterSpacing: `-0.07200000107288361px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  height: `30px`,  
  width: `1200px`,  
  margin: `20px 0px 0px 0px`,  
}));
  
const Buttons1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `20px 0px 0px 0px`,  
});
  
const InputsLedger = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  border: `1px solid rgba(224, 224, 224, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `12px 8px`,  
  boxSizing: `border-box`,  
  width: `300px`,  
  margin: `0px`,  
  overflow: `hidden`,  
}));
  
const Group45 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `16px`,  
  width: `264px`,  
  margin: `0px`,  
});
  
const Group213 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `264px`,  
  height: `16px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const EnterYourEmailAddres = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(148, 148, 148, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Text`,  
  fontWeight: `500`,  
  fontSize: `14px`,  
  letterSpacing: `-0.28px`,  
  textDecoration: `none`,  
  lineHeight: `16px`,  
  textTransform: `none`,  
  width: `264px`,  
  height: `16px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
}));
  
const FccButtons1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 16px`,  
});
  
const LightButton1 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(211, 54, 139, 1)`,  
  boxShadow: `0px 1px 3px rgba(0, 0, 0, 0.08)`,  
  border: `1px solid rgba(211, 54, 139, 1)`,  
  borderRadius: `3px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `12px 16px`,  
  boxSizing: `border-box`,  
  width: `186px`,  
  margin: `0px`,  
  cursor: `pointer`,  
}));
  
const GetEarlyAccess = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Text`,  
  fontWeight: `600`,  
  fontSize: `16px`,  
  letterSpacing: `-0.32px`,  
  textDecoration: `none`,  
  lineHeight: `16px`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Union = styled("img")({  
  height: `12.67px`,  
  width: `14px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const NumberCallout1 = styled(NumberCallout)(({ theme }) =>({  
  height: `450px`,  
  width: `1044px`,  
  margin: `0px`,  
}));
  
const Hr = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  alignSelf: `stretch`,  
  height: `1px`,  
  margin: `0px`,  
});
  
const Collophon = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `60px 0px`,  
  boxSizing: `border-box`,  
  height: `450px`,  
  margin: `0px`,  
});
  
const Text = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Q200CompaniesTrustFi = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Text`,  
  fontWeight: `600`,  
  fontSize: `40px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `48px`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Logos = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `121px`,  
  width: `1100px`,  
  margin: `32px 0px 0px 0px`,  
  overflow: `hidden`,  
});
  
const PimcoFundsLogoBlackA = styled("img")({  
  height: `49px`,  
  width: `180px`,  
  position: `absolute`,  
  left: `116px`,  
  top: `72px`,  
});
  
const Image7 = styled("img")({  
  height: `38.01px`,  
  width: `180px`,  
  position: `absolute`,  
  left: `920px`,  
  top: `2px`,  
});
  
const Image8 = styled("img")({  
  height: `36px`,  
  width: `199px`,  
  position: `absolute`,  
  left: `451px`,  
  top: `3px`,  
});
  
const Image9 = styled("img")({  
  height: `47.29px`,  
  width: `180px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `-2px`,  
});
  
const Image10 = styled("img")({  
  height: `15.08px`,  
  width: `180px`,  
  position: `absolute`,  
  left: `230px`,  
  top: `15px`,  
});
  
const Image14 = styled("img")({  
  height: `44.8px`,  
  width: `180px`,  
  position: `absolute`,  
  left: `345px`,  
  top: `76px`,  
});
  
const Image12 = styled("img")({  
  height: `38px`,  
  width: `180px`,  
  position: `absolute`,  
  left: `576px`,  
  top: `75px`,  
});
  
const Image6 = styled("img")({  
  height: `43px`,  
  width: `168px`,  
  position: `absolute`,  
  left: `696px`,  
  top: `5px`,  
});
  
const Image13 = styled("img")({  
  height: `39px`,  
  width: `180px`,  
  position: `absolute`,  
  left: `805px`,  
  top: `77px`,  
});
  
const Hr1 = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  alignSelf: `stretch`,  
  height: `1px`,  
  margin: `0px`,  
});
  
const Blocks = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `32px 207px 32px 0px`,  
  boxSizing: `border-box`,  
  height: `450px`,  
  width: `1155px`,  
  margin: `0px`,  
});
  
const Kvp = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 12px 0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const KeyVauePropositionTe = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `700`,  
  fontSize: `11px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Title = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 12px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const LoremIpsumDolorSitAm = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `900`,  
  fontSize: `36px`,  
  letterSpacing: `-1.08px`,  
  textDecoration: `none`,  
  lineHeight: `34px`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Description = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 24px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const LoremIpsumDolorSitAm1 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Buttons2 = styled(Buttons)(({ theme }) =>({  
  margin: `0px`,  
}));
  
const Hr2 = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  alignSelf: `stretch`,  
  height: `1px`,  
  margin: `0px`,  
});
  
const Blocks1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `32px 0px`,  
  boxSizing: `border-box`,  
  height: `450px`,  
  width: `1155px`,  
  margin: `0px`,  
});
  
const MediaContent = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  width: `600px`,  
  height: `300px`,  
  margin: `0px`,  
});
  
const TextWrapper = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  width: `523px`,  
  margin: `0px 0px 0px 32px`,  
});
  
const Kvp1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 12px 0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const KeyVauePropositionTe1 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `700`,  
  fontSize: `11px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Title1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 12px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const LoremIpsumDolorSitAm2 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `900`,  
  fontSize: `36px`,  
  letterSpacing: `-1.08px`,  
  textDecoration: `none`,  
  lineHeight: `34px`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Description1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 24px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const LoremIpsumDolorSitAm3 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Buttons3 = styled(Buttons)(({ theme }) =>({  
  margin: `0px`,  
}));
  
const Hr3 = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  alignSelf: `stretch`,  
  height: `1px`,  
  margin: `0px`,  
});
  
const Blocks2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `32px 0px`,  
  boxSizing: `border-box`,  
  height: `450px`,  
  width: `1155px`,  
  margin: `0px`,  
});
  
const TextWrapper1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  width: `523px`,  
  margin: `0px`,  
});
  
const Kvp2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 12px 0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const KeyVauePropositionTe2 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `700`,  
  fontSize: `11px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Title2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 12px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const LoremIpsumDolorSitAm4 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `900`,  
  fontSize: `36px`,  
  letterSpacing: `-1.08px`,  
  textDecoration: `none`,  
  lineHeight: `34px`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Description2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 24px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const LoremIpsumDolorSitAm5 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Buttons4 = styled(Buttons)(({ theme }) =>({  
  margin: `0px`,  
}));
  
const MediaContent1 = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  width: `600px`,  
  height: `300px`,  
  margin: `0px 0px 0px 32px`,  
});
  
const Rectangle1383 = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  alignSelf: `stretch`,  
  height: `1px`,  
  margin: `0px`,  
});
  
const Frame288 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `32px 200px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `450px`,  
  margin: `0px`,  
});
  
const Kvp3 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 12px 0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const KeyVauePropositionTe3 = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `700`,  
  fontSize: `11px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Title3 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 12px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const LoremIpsumDolorSitAm6 = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `900`,  
  fontSize: `36px`,  
  letterSpacing: `-1.08px`,  
  textDecoration: `none`,  
  lineHeight: `34px`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Description3 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 24px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const LoremIpsumDolorSitAm7 = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Buttons5 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const InputsLedger1 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  border: `1px solid rgba(224, 224, 224, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `12px 8px`,  
  boxSizing: `border-box`,  
  width: `300px`,  
  margin: `0px`,  
  overflow: `hidden`,  
}));
  
const Group451 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `16px`,  
  width: `271px`,  
  margin: `0px`,  
});
  
const Group2131 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `271px`,  
  height: `16px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const EnterYourEmailAddres1 = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(148, 148, 148, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Text`,  
  fontWeight: `500`,  
  fontSize: `14px`,  
  letterSpacing: `-0.28px`,  
  textDecoration: `none`,  
  lineHeight: `16px`,  
  textTransform: `none`,  
  width: `271px`,  
  height: `16px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
}));
  
const FccButtons2 = styled(FccButtons)(({ theme }) =>({  
  height: `40px`,  
  margin: `0px 0px 0px 16px`,  
}));
  
const Rectangle1384 = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  alignSelf: `stretch`,  
  height: `1px`,  
  margin: `0px`,  
});
  
const Blocks3 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(26, 26, 26, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px 200px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `450px`,  
  margin: `0px`,  
}));
  
const Kvp4 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 12px 0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const KeyVauePropositionTe4 = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(245, 245, 245, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `700`,  
  fontSize: `11px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Title4 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 12px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const LoremIpsumDolorSitAm8 = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(245, 245, 245, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `900`,  
  fontSize: `36px`,  
  letterSpacing: `-1.08px`,  
  textDecoration: `none`,  
  lineHeight: `34px`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px`,  
}));
  
const Description4 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 24px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const LoremIpsumDolorSitAm9 = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(214, 214, 214, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Display`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px`,  
}));
  
const Buttons6 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const FccButtons3 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `40px`,  
  margin: `0px`,  
});
  
const LightButton2 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(211, 54, 139, 1)`,  
  boxShadow: `0px 1px 3px rgba(0, 0, 0, 0.08)`,  
  border: `1px solid rgba(211, 54, 139, 1)`,  
  borderRadius: `3px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `8px 12px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
  
const GetEarlyAccess1 = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Text`,  
  fontWeight: `600`,  
  fontSize: `14px`,  
  letterSpacing: `-0.28px`,  
  textDecoration: `none`,  
  lineHeight: `16px`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Icons12PxArrowRight = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `16px`,  
  height: `16px`,  
  margin: `0px 0px 0px 8px`,  
  overflow: `hidden`,  
});
  
const Union1 = styled("img")({  
  height: `12.67px`,  
  width: `14px`,  
  position: `absolute`,  
  left: `1px`,  
  top: `2px`,  
});
  
const InputsLedger2 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  border: `1px solid rgba(224, 224, 224, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `12px 8px`,  
  boxSizing: `border-box`,  
  width: `300px`,  
  margin: `0px 0px 0px 16px`,  
  overflow: `hidden`,  
}));
  
const Group452 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `16px`,  
  width: `271px`,  
  margin: `0px`,  
});
  
const Group2132 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `271px`,  
  height: `16px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const EnterYourEmailAddres2 = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(148, 148, 148, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `SF Pro Text`,  
  fontWeight: `500`,  
  fontSize: `14px`,  
  letterSpacing: `-0.28px`,  
  textDecoration: `none`,  
  lineHeight: `16px`,  
  textTransform: `none`,  
  width: `271px`,  
  height: `16px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
}));
  
const Rectangle1385 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(146, 32, 93, 1)`,  
  alignSelf: `stretch`,  
  height: `1px`,  
  margin: `0px`,  
}));
  
const Footer1 = styled(Footer)(({ theme }) =>({  
  alignSelf: `stretch`,  
  height: `450px`,  
  margin: `0px`,  
}));
 
function Q001Home() {
  const {fns} = useQ001Home();
  return (
    <Q001Home1 >
       <TopNav1   />
       <Hero >
         <FitchCreditCertifica >
           {`Fitch Credit Certifications validate your skills and open doors for career advancement`}
             </FitchCreditCertifica>
         <Q78OfCertifiedProfes >
           {`78% of certified professionals have experienced greater demand for their skills since becoming certified.`}
             </Q78OfCertifiedProfes>
         <Buttons1 >
           <InputsLedger >
             <Group45 >
               <Group213 >
                 <EnterYourEmailAddres >
                   {`Enter your email address`}
                     </EnterYourEmailAddres>
               </Group213>
             </Group45>
           </InputsLedger>
           <FccButtons1 >
             <LightButton1 onClick={fns.handleClick} >
               <GetEarlyAccess >
                 {`Get Early Access`}
                   </GetEarlyAccess>
               <Union  src={UnionImage} alt={"Union"}/>
             </LightButton1>
           </FccButtons1>
         </Buttons1>
       </Hero>
       <NumberCallout1   />
       <Hr >
       </Hr>
       <Collophon >
         <Text >
           <Q200CompaniesTrustFi >
             {`200+ Companies trust Fitch Learning
with Credit Certifications`}
               </Q200CompaniesTrustFi>
         </Text>
         <Logos >
           <PimcoFundsLogoBlackA  src={PimcoFundsLogoBlackAImage} alt={"pimco-funds-logo-black-and-white 1"}/>
           <Image7  src={Image7Image} alt={"image 7"}/>
           <Image8  src={Image8Image} alt={"image 8"}/>
           <Image9  src={Image9Image} alt={"image 9"}/>
           <Image10  src={Image10Image} alt={"image 10"}/>
           <Image14  src={Image14Image} alt={"image 14"}/>
           <Image12  src={Image12Image} alt={"image 12"}/>
           <Image6  src={Image6Image} alt={"image 6"}/>
           <Image13  src={Image13Image} alt={"image 13"}/>
         </Logos>
       </Collophon>
       <Hr1 >
       </Hr1>
       <Blocks >
         <Kvp >
           <KeyVauePropositionTe >
             {`KEY VAUE PROPOSITION TEXT ONLY`}
               </KeyVauePropositionTe>
         </Kvp>
         <Title >
           <LoremIpsumDolorSitAm >
             {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eget rutrum leo. Aliquam id pellentesque enim. Aenean nec massa volutpat, fermentum orci quis.`}
               </LoremIpsumDolorSitAm>
         </Title>
         <Description >
           <LoremIpsumDolorSitAm1 >
             {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eget rutrum leo. Aliquam id pellentesque enim. Aenean nec massa volutpat, fermentum orci quis, porttitor nibh. Quisque enim massa, semper nec maximus nec, volutpat eget nulla. Cras quis mauris at elit ornare vestibulum. Praesent vel lorem condimentum, rutrum nisl ut, malesuada odio. Fusce sagittis mauris est.`}
               </LoremIpsumDolorSitAm1>
         </Description>
         <Buttons2   />
       </Blocks>
       <Hr2 >
       </Hr2>
       <Blocks1 >
         <MediaContent >
         </MediaContent>
         <TextWrapper >
           <Kvp1 >
             <KeyVauePropositionTe1 >
               {`KEY VAUE PROPOSITION TEXT ONLY`}
                 </KeyVauePropositionTe1>
           </Kvp1>
           <Title1 >
             <LoremIpsumDolorSitAm2 >
               {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eget rutrum leo`}
                 </LoremIpsumDolorSitAm2>
           </Title1>
           <Description1 >
             <LoremIpsumDolorSitAm3 >
               {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eget rutrum leo. Aliquam id pellentesque enim. Aenean nec massa volutpat, fermentum orci quis, porttitor nibh. Quisque enim massa, semper nec maximus nec, volutpat eget nulla. Cras quis mauris at elit ornare vestibulum. Praesent vel lorem condimentum, rutrum nisl ut, malesuada odio. Fusce sagittis mauris est.`}
                 </LoremIpsumDolorSitAm3>
           </Description1>
           <Buttons3   />
         </TextWrapper>
       </Blocks1>
       <Hr3 >
       </Hr3>
       <Blocks2 >
         <TextWrapper1 >
           <Kvp2 >
             <KeyVauePropositionTe2 >
               {`KEY VAUE PROPOSITION TEXT ONLY`}
                 </KeyVauePropositionTe2>
           </Kvp2>
           <Title2 >
             <LoremIpsumDolorSitAm4 >
               {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eget rutrum leo`}
                 </LoremIpsumDolorSitAm4>
           </Title2>
           <Description2 >
             <LoremIpsumDolorSitAm5 >
               {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eget rutrum leo. Aliquam id pellentesque enim. Aenean nec massa volutpat, fermentum orci quis, porttitor nibh. Quisque enim massa, semper nec maximus nec, volutpat eget nulla. Cras quis mauris at elit ornare vestibulum. Praesent vel lorem condimentum, rutrum nisl ut, malesuada odio. Fusce sagittis mauris est.`}
                 </LoremIpsumDolorSitAm5>
           </Description2>
           <Buttons4   />
         </TextWrapper1>
         <MediaContent1 >
         </MediaContent1>
       </Blocks2>
       <Rectangle1383 >
       </Rectangle1383>
       <Frame288 >
         <Kvp3 >
           <KeyVauePropositionTe3 >
             {`KEY VAUE PROPOSITION TEXT ONLY`}
               </KeyVauePropositionTe3>
         </Kvp3>
         <Title3 >
           <LoremIpsumDolorSitAm6 >
             {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eget rutrum leo. Aliquam id pellentesque enim. Aenean nec massa volutpat, fermentum orci quis.`}
               </LoremIpsumDolorSitAm6>
         </Title3>
         <Description3 >
           <LoremIpsumDolorSitAm7 >
             {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eget rutrum leo. Aliquam id pellentesque enim. Aenean nec massa volutpat, fermentum orci quis, porttitor nibh. Quisque enim massa, semper nec maximus nec, volutpat eget nulla. Cras quis mauris at elit ornare vestibulum. Praesent vel lorem condimentum, rutrum nisl ut, malesuada odio. Fusce sagittis mauris est.`}
               </LoremIpsumDolorSitAm7>
         </Description3>
         <Buttons5 >
           <InputsLedger1 >
             <Group451 >
               <Group2131 >
                 <EnterYourEmailAddres1 >
                   {`Enter your email address`}
                     </EnterYourEmailAddres1>
               </Group2131>
             </Group451>
           </InputsLedger1>
           <FccButtons2   />
         </Buttons5>
       </Frame288>
       <Rectangle1384 >
       </Rectangle1384>
       <Blocks3 >
         <Kvp4 >
           <KeyVauePropositionTe4 >
             {`KEY VAUE PROPOSITION TEXT ONLY`}
               </KeyVauePropositionTe4>
         </Kvp4>
         <Title4 >
           <LoremIpsumDolorSitAm8 >
             {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eget rutrum leo. Aliquam id pellentesque enim. Aenean nec massa volutpat, fermentum orci quis.`}
               </LoremIpsumDolorSitAm8>
         </Title4>
         <Description4 >
           <LoremIpsumDolorSitAm9 >
             {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eget rutrum leo. Aliquam id pellentesque enim. Aenean nec massa volutpat, fermentum orci quis, porttitor nibh. Quisque enim massa, semper nec maximus nec, volutpat eget nulla. Cras quis mauris at elit ornare vestibulum. Praesent vel lorem condimentum, rutrum nisl ut, malesuada odio. Fusce sagittis mauris est.`}
               </LoremIpsumDolorSitAm9>
         </Description4>
         <Buttons6 >
           <FccButtons3 >
             <LightButton2 >
               <GetEarlyAccess1 >
                 {`Get Early Access`}
                   </GetEarlyAccess1>
               <Icons12PxArrowRight >
                 <Union1  src={Union1Image} alt={"Union"}/>
               </Icons12PxArrowRight>
             </LightButton2>
           </FccButtons3>
           <InputsLedger2 >
             <Group452 >
               <Group2132 >
                 <EnterYourEmailAddres2 >
                   {`Enter your email address`}
                     </EnterYourEmailAddres2>
               </Group2132>
             </Group452>
           </InputsLedger2>
         </Buttons6>
       </Blocks3>
       <Rectangle1385 >
       </Rectangle1385>
       <Footer1   />
     </Q001Home1>
   );
}

export default Q001Home;
